import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ClerkProvider, SignedIn } from "@clerk/nextjs";
import { eb_garamond } from "@/styles/fonts";
import "../styles/global.css";

//! Update metadata to match your project
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <SignedIn>
            <Navbar />
          </SignedIn>
          <div className={`${eb_garamond.className}`}>{children}</div>
          {/* <SignedIn>
            <Footer />
          </SignedIn> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
